# Dataset Analysis

## FILE 1 PROVA

In [1]:
file_code = 'MMSE'

In [2]:
import pandas as pd
import numpy as np
from dl_client import DatalakeClient

client = DatalakeClient()

In [3]:
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True
)

dataset = zip_files[list(zip_files.keys())[0]]

In [25]:
dataset

,PHASE,PTID,RID,VISCODE,VISCODE2,VISDATE,DONE,NDREASON,SOURCE,MMDATE,...,MMDRAW,MMSCORE,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
0,ADNI1,011_S_0002,2,sc,sc,2005-08-17,NaN,NaN,NaN,1.0,...,1.0,28.0,10,107,2005-08-17,NaN,NaN,NaN,NaN,2024-08-22 07:18:34.0
1,ADNI1,022_S_0001,1,f,f,2005-08-18,NaN,NaN,NaN,1.0,...,0.0,28.0,12,10,2005-08-18,NaN,NaN,NaN,NaN,2024-08-22 07:18:34.0
2,ADNI1,011_S_0003,3,sc,sc,2005-08-18,NaN,NaN,NaN,0.0,...,1.0,20.0,14,107,2005-08-18,NaN,NaN,NaN,NaN,2024-08-22 07:18:34.0
3,ADNI1,022_S_0004,4,sc,sc,2005-08-18,NaN,NaN,NaN,1.0,...,0.0,27.0,16,10,2005-08-18,NaN,NaN,NaN,NaN,2024-08-22 07:18:34.0
4,ADNI1,011_S_0005,5,sc,sc,2005-08-23,NaN,NaN,NaN,1.0,...,1.0,29.0,18,107,2005-08-23,NaN,NaN,NaN,NaN,2024-08-22 07:18:34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14332,ADNI4,010_S_6748,6748,4_init,m72,2025-06-03,1.0,NaN,1.0,1.0,...,0.0,29.0,96499,10,2025-06-03,2025-06-03,v1,e,0.0,2025-06-05 01:43:43.0
14333,ADNI4,123_S_10816,10816,4_sc,sc,2025-06-03,1.0,NaN,1.0,1.0,...,1.0,28.0,96576,123,2025-06-03,2025-06-03,v1,e,0.0,2025-06-05 01:43:43.0
14334,ADNI4,127_S_6436,6436,4_init,m84,2025-05-20,1.0,NaN,1.0,1.0,...,1.0,30.0,96628,127,2025-06-03,2025-06-03,v1,e,0.0,2025-06-05 01:43:43.0
14335,ADNI4,082_S_10809,10809,4_sc,sc,2025-06-03,1.0,NaN,1.0,1.0,...,1.0,30.0,96644,82,2025-06-03,2025-06-03,v1,e,0.0,2025-06-05 01:43:43.0
14336,ADNI4,002_S_10814,10814,4_sc,sc,2025-06-02,1.0,NaN,1.0,1.0,...,1.0,29.0,96987,2,2025-06-04,2025-06-04,v1,e,0.0,2025-06-06 01:42:37.0

In [45]:
dataset['ID']

0           10
1           12
2           14
3           16
4           18
         ...
14332    96499
14333    96576
14334    96628
14335    96644
14336    96987
Name: ID, Length: 14337, dtype: int64

In [31]:
dataset['VISCODE'].unique()

array(['sc', 'f', 'm06', 'm12', 'm18', 'm36', 'm24', 'm48', 'm60', 'm72',
       'v01', 'v06', 'v11', 'v05', 'v21', 'v31', 'v41', 'v51', 'tau',
       'y1', 'y2', 'init', 'y4', 'y3', 'y5', '4_sc', '4_init', '4_m12'],
      dtype=object)

In [4]:
dataset['VISCODE2'].unique()

array(['sc', 'f', 'm06', 'm12', 'm18', 'm36', 'm24', 'm48', 'm60', 'm72',
       'm84', 'm96', 'm108', 'm120', 'm42', 'm132', 'm54', 'm30', 'm126',
       'm138', 'm150', 'm174', 'm66', 'm90', 'm78', 'm102', 'm114',
       'm144', 'm156', 'm180', nan, 'm186', 'm162', 'm198', 'm168',
       'm192', 'm204', 'm210', 'm216', 'm222', 'm228'], dtype=object)

In [42]:
# Find idex in the dataframe of row in which viscode2 is null
viscode2_null_index = dataset[dataset['VISCODE2'].isnull()].index
data_filter = dataset[dataset.index.isin(viscode2_null_index)]

In [20]:
dataset_with_f = dataset[dataset['VISCODE2'] == 'sc'].copy(deep=True)

In [22]:
count = 0

for index, row in dataset_with_f.iterrows():
    patient = dataset[dataset['PTID'] == row['PTID']]
    if patient.shape[0] > 1:
        count += 1

print(count, dataset_with_f.shape[0])

2210 4225

In [43]:
data_filter

,PHASE,PTID,RID,VISCODE,VISCODE2,VISDATE,DONE,NDREASON,SOURCE,MMDATE,...,MMDRAW,MMSCORE,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
10137,ADNI3,016_S_4951,4951,y1,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,178100,12,2023-09-11,2023-09-11,NaN,NaN,NaN,2023-09-12 04:29:19.0
10319,ADNI3,941_S_5193,5193,y4,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,156150,59,2022-05-06,2022-05-06,NaN,NaN,NaN,2022-05-07 04:21:37.0
10387,ADNI3,123_S_1300,1300,y1,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,185111,45,2025-01-15,2025-01-15,NaN,NaN,NaN,2025-01-17 04:38:05.0
10916,ADNI3,116_S_6624,6624,y2,NaN,NaN,0.0,3.0,NaN,NaN,...,NaN,NaN,123700,44,2020-11-19,2020-11-19,NaN,NaN,NaN,2020-11-19 15:29:44.0
11104,ADNI3,941_S_6514,6514,y4,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,165072,59,2022-09-07,2022-09-07,NaN,NaN,NaN,2022-09-08 04:21:59.0
11229,ADNI3,023_S_0031,31,y4,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,151449,18,2022-02-21,2022-02-21,NaN,NaN,NaN,2022-02-22 04:22:07.0
11253,ADNI3,116_S_4483,4483,y3,NaN,NaN,0.0,3.0,NaN,NaN,...,NaN,NaN,145349,44,2021-10-26,2021-10-26,NaN,NaN,NaN,2021-10-27 04:21:37.0
11648,ADNI3,941_S_4420,4420,y3,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,172220,59,2023-01-20,2023-01-20,NaN,NaN,NaN,2023-01-21 04:27:57.0
11695,ADNI3,941_S_4100,4100,y4,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,165010,59,2022-09-07,2022-09-07,NaN,NaN,NaN,2022-09-08 04:21:58.0
11782,ADNI3,023_S_2068,2068,y1,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,97595,18,2019-09-24,2019-09-24,NaN,NaN,NaN,2019-11-13 11:16:40.0
11936,ADNI3,135_S_5273,5273,y2,NaN,NaN,0.0,3.0,NaN,NaN,...,NaN,NaN,100318,52,2019-10-22,2019-10-22,NaN,NaN,NaN,2019-11-13 11:16:40.0
12010,ADNI3,129_S_6082,6082,y1,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,84690,49,2019-06-03,2019-06-03,NaN,NaN,NaN,2019-11-13 11:16:40.0
12380,ADNI3,002_S_4225,4225,y2,NaN,NaN,0.0,8.0,NaN,NaN,...,NaN,NaN,180262,1,2024-02-27,2024-02-27,NaN,NaN,NaN,2024-02-28 04:32:06.0
12635,ADNI3,141_S_6779,6779,y2,NaN,NaN,0.0,3.0,NaN,NaN,...,NaN,NaN,149475,55,2022-01-10,2022-01-10,NaN,NaN,NaN,2022-08-22 15:17:27.0
13121,ADNI4,011_S_7112,7112,4_init,NaN,2023-11-29,1.0,NaN,1.0,1.0,...,0.0,24.0,3222,11,2023-11-29,2023-11-29,v1,e,0.0,2023-11-30 00:17:58.0
13717,ADNI4,013_S_6970,6970,4_init,NaN,2024-10-08,1.0,NaN,1.0,0.0,...,1.0,22.0,46960,13,2024-11-06,2025-03-28,v1,e,0.0,2025-03-29 01:42:39.0
14280,ADNI4,153_S_10417,10417,4_sc,NaN,2025-05-08,1.0,NaN,1.0,1.0,...,1.0,27.0,92600,153,2025-05-15,2025-05-15,v1,e,0.0,2025-05-17 01:41:00.0
14286,ADNI4,389_S_10790,10790,4_sc,NaN,2025-05-16,1.0,NaN,1.0,0.0,...,1.0,28.0,92781,389,2025-05-16,2025-05-16,v1,e,0.0,2025-05-18 01:46:51.0

In [28]:
dataset[dataset['PTID'] == '002_S_10814']

,PHASE,PTID,RID,VISCODE,VISCODE2,VISDATE,DONE,NDREASON,SOURCE,MMDATE,...,MMDRAW,MMSCORE,ID,SITEID,USERDATE,USERDATE2,DD_CRF_VERSION_LABEL,LANGUAGE_CODE,HAS_QC_ERROR,update_stamp
14336,ADNI4,002_S_10814,10814,4_sc,sc,2025-06-02,1.0,NaN,1.0,1.0,...,1.0,29.0,96987,2,2025-06-04,2025-06-04,v1,e,0.0,2025-06-06 01:42:37.0

In [5]:
dataset.columns

Index(['PTID', 'RID', 'VISCODE2', 'NPFORMMO', 'NPFORMDY', 'NPFORMYR',
       'NPFORMDATE_DRVD', 'NPDAGE', 'NPDODYR', 'NPPMIH',
       ...
       'NPATGAM2', 'NPATGAM3', 'NPATGAM4', 'NPATGAM5', 'NPATGFRN', 'NPATGFR1',
       'NPATGFR2', 'NPATGFR3', 'NPATGFR4', 'update_stamp'],
      dtype='object', length=164)

## File 2

In [11]:
file_code = 'BLCHANGE'

In [12]:
import pandas as pd
import numpy as np
from dl_client import DatalakeClient

client = DatalakeClient()

In [13]:
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True
)

dataset = zip_files[list(zip_files.keys())[0]]

In [16]:
dataset['VISCODE'].unique()

array(['bl', 'm06', 'm12', 'uns1', 'm18', 'm24', 'm36', 'm48', 'm60',
       'm72', 'v01', 'v06', 'v03', 'v05', 'v11', 'v21', 'v31', 'v41',
       'v51', 'init', 'sc', 'y1', 'y5', 'y2', 'y4', 'y3', '4_init',
       '4_sc', '4_bl', '4_m12'], dtype=object)

In [17]:
dataset['VISCODE2']

0         bl
1         bl
2         bl
3         bl
4         bl
        ...
15239     sc
15240     bl
15241     bl
15242    m78
15243     bl
Name: VISCODE2, Length: 15244, dtype: object