# ADNI

## INIT

In [2]:
from data_model.DataCleaner import DataCleaner, update_variables_support_file
from dl_client import DatalakeClient
from tests_utils.manage_excel_support_file import *
import pandas as pd
import os


dataCleaner = DataCleaner(support_file_path='ADNI_variables_statistics.xlsx')
client = DatalakeClient()

# Download the raw files 
Exclusevily from ADNI dataset stored in the Datalake

In [2]:
file_codes = ['BAIPETNMRCFTP',
'AMPRION_ASYN_SAA',
'PLASMA_ABETA_PROJECT_ADX_VUMC',
'FNIH_PLASMA_PTAU_PROJECT',
'CSFALPHASYN',
'BLENNOWCSFNFL',
'UPENNPLASMA',
'BLENNOWPLASMANFL',
'BLENNOWPLASMATAU',
'C2N_PRECIVITYAD2_PLASMA',
'UGOTPTAU181',
'UPENN_PLASMA_FUJIREBIO_QUANTERIX',
'UCBERKELEY_AMY_6MM',
'UCBERKELEY_TAUPVC_6MM']

In [3]:
search = client.query_files(
    query={'custom.level' : 'raw', 'custom.source' : 'ADNI', 'custom.file_code' : file_codes})

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True)

print(zip_files.keys())
print(len(zip_files.keys()))

dict_keys(['AMPRION_ASYN_SAA_11Aug2025.csv', 'BAIPETNMRCFTP_08_17_22_11Aug2025.csv', 'BLENNOWCSFNFL_11Aug2025.csv', 'ADNI_BLENNOWPLASMANFLLONG_10_03_18_11Aug2025.csv', 'ADNI_BLENNOWPLASMANFL_10_03_18_11Aug2025.csv', 'BLENNOWPLASMATAU_11Aug2025.csv', 'C2N_PRECIVITYAD2_PLASMA_11Aug2025.csv', 'CSFALPHASYN_03_21_14_11Aug2025.csv', 'FNIH_PLASMA_PTAU_PROJECT_11Aug2025.csv', 'PLASMA_ABETA_PROJECT_ADX_VUMC_11Aug2025.csv', 'UCBERKELEY_AMY_6MM_28Oct2025.csv', 'UCBERKELEY_TAUPVC_6MM_28Oct2025.csv', 'UGOTPTAU181_06_18_20_28Oct2025.csv', 'UPENNPLASMA_28Oct2025.csv', 'UPENN_PLASMA_FUJIREBIO_QUANTERIX_28Oct2025.csv'])
15

# Support file managment
operazione per popolare il file support file per i file considerati

In [4]:
support_file_path = 'ADNI_variables_statistics'
support_file = pd.read_excel(support_file_path+'.xlsx')

In [ ]:
support_file_path = 'ADNI_variables_statistics'
support_file = pd.read_excel(support_file_path+'.xlsx')
for file_name in list(zip_files.keys()):
    df = zip_files[file_name]
    infoSupportFile = InfoSupportFile(support_file, df, file_name)
    # delate the rows of the support file that are not in the df
    support_file, file_code = infoSupportFile.filter_variables()
    print(file_code)
    if file_code not in list(support_file['file_code']):
        print('not found in excel')
        continue
    # find the population variable code, and if not in support_file, add it
    pop, support_file = infoSupportFile.find_population_variable()
    # get the variable info and add it to the support_file    
    for key in df.keys():
        if key in support_file[support_file['file_code'] == file_code]['variable_code'].values:
            infoSupportFile.get_varible_info(key)
# save the updated support file
save_df(df_to_save=support_file, output_path=support_file_path)

In [ ]:
for file_name in list(zip_files.keys()):
    df = zip_files[file_name]
    infoSupportFile = InfoSupportFile(support_file, df, file_name)
    # delate the rows of the support file that are not in the df
    support_file, file_code = infoSupportFile.filter_variables()
    print(file_code)
    if file_code not in list(support_file['file_code']):
        print('not found in excel')
        continue
    # find the population variable code, and if not in support_file, add it
    pop, support_file = infoSupportFile.find_population_variable()
    # get the variable info and add it to the support_file    
    for key in df.keys():
        if key in support_file[support_file['file_code'] == file_code]['variable_code'].values:
            infoSupportFile.get_varible_info(key)
# save the updated support file
save_df(df_to_save=support_file, output_path=support_file_path)

In [9]:
new_support_file_name = 'ADNI_variables_cleaned_BB'
if os.path.isfile(new_support_file_name+'.xlsx'):
    update_new_support_file(support_file, new_support_file_name, processed_file=file_codes)
else:
    create_new_support_file(support_file, support_file_path, new_name=new_support_file_name)

The ADNI_variables_cleaned_BB file has been created.
Open the file and verify it, if needed update the variables names and metadata

## IF SUPPORT FILE already populated

In [5]:
support_file_path = 'ADNI_variables_statistics'
support_file = pd.read_excel(support_file_path+'.xlsx')

new_support_file_name = 'ADNI_variables_cleaned_BB'
if os.path.isfile(new_support_file_name+'.xlsx'):
    update_new_support_file(support_file, new_support_file_name, processed_file=file_codes)
else:
    create_new_support_file(support_file, support_file_path, new_name=new_support_file_name)

The ADNI_variables_cleaned_BB file has been updated with the new file_code: []
Open the file and verify it, if needed update the variables names and metadata
The ADNI_variables_cleaned_BB file has restored the previous information of the file_code: []
Open the file and verify it, if needed update the variables names and metadata

In [6]:
support_file_path = 'ADNI_variables_statistics'
support_file = pd.read_excel(support_file_path+'.xlsx')

new_support_file_name = 'ADNI_variables_cleaned_BB'

Open the new_support_file and fill in the new variable codes.

# FILE SPECIFIC DATA CLEANING 1

PLASMA_ABETA_PROJECT_ADX_VUMC

In [4]:
file_code = 'PLASMA_ABETA_PROJECT_ADX_VUMC' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['NF_LIGHT','ABETA42', 'ABETA40', 'GFAP' ]
# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
# datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'simoa' # write method manually, if not known unknown
#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  
# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)
# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
Nessuna regione Tau disponibile — TAU_METAROI non creata.

,RID,VISCODE,VISIT_MONTH,EXAMDATE,NFL_PL,AB42_PL,AB40_PL,GFAP,METHOD,Apositive,Npositive
0,31,m120,0,2016-01-27,48.7,7.2,168.3,145.0,simoa,1,1
1,138,m120,0,2016-02-18,49.3,9.3,173.6,142.6,simoa,1,1
2,150,m120,0,2016-03-16,27.8,5.9,125.8,114.1,simoa,1,1
3,214,m120,0,2016-03-29,28.9,6.9,124.1,107.1,simoa,1,1
4,303,m132,0,2017-04-12,36.9,9.2,200.2,167.4,simoa,1,1

In [5]:
var_of_interest = ['NFL_PL','AB42_PL', 'AB40_PL', 'GFAP' ]
df_interest = final_df[final_df['METHOD']=='simoa'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
        1° percentile 99° percentile
NFL_PL         11.745         67.678
AB42_PL         4.687         12.026
AB40_PL        89.451        307.752
GFAP           44.596        450.186
totale subject: 121
subjects with multiple visits:  9

In [7]:
# optaining automatically info to save the file
#lst_population = infoSupportFile.get_present_populations()
lst_population = ['ADNI2','ADNI3']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')
# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

C2N

In [9]:
file_code = 'C2N_PRECIVITYAD2_PLASMA' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['AB42_C2N', 'AB40_C2N', 'AB42_AB40_C2N', 'pT217_npT217_C2N', 'APOE_C2N', 'pT217_C2N', 'npT217_C2N']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'massospectrometry' # write method manually, if not known unknown

processed_df = dataCleaner.uniform_APOE_format(df=datefix_df, col_name='APOE_C2N')
processed_df = dataCleaner.APOE_4_count(df=processed_df, col_name='APOE_C2N')

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD', 'APOE_4'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()

renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
Nessuna regione Tau disponibile — TAU_METAROI non creata.

,COHORT,RID,VISCODE,VISIT_MONTH,EXAMDATE,PT217_PL,nPT217_PL,AB42_PL,AB40_PL,AB4240_PL,PT217_nPT217_PL,APOE,COMMENTS,METHOD,Apositive,Tpositive
0,ADNI4,69,m216,0,2024-04-01,2.709,78.306,62.669,671.452,0.093,3.46,E3/E3,NaN,massospectrometry,1,0
1,ADNI4,89,m216,0,2023-11-29,0.650,47.139,38.970,406.884,0.096,1.38,E3/E3,p-tau217 LOD,massospectrometry,1,0
2,ADNI4,337,m210,0,2023-10-23,3.635,109.686,62.596,719.192,0.087,3.31,E3/E4,Sample Corrected for Dilution p-tau,massospectrometry,1,0
3,ADNI4,908,m204,0,2024-01-10,1.436,75.437,62.768,517.230,0.121,1.90,E2/E3,NaN,massospectrometry,1,0
4,ADNI4,908,m222,12,2025-01-23,1.833,56.085,59.112,519.406,0.114,3.27,E2/E3,NaN,massospectrometry,1,0

In [10]:
var_of_interest = ['PT217_PL', 'nPT217_PL',	'AB42_PL',	'AB40_PL',	'AB4240_PL','PT217_nPT217_PL']
df_interest=final_df[final_df['METHOD']=='massospectrometry'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
                1° percentile 99° percentile
PT217_PL                 0.65        13.4561
nPT217_PL             23.5012       128.2975
AB42_PL               29.4746        84.8812
AB40_PL              285.9777       831.5726
AB4240_PL               0.076          0.135
PT217_nPT217_PL          0.73        18.4044
totale subject: 620
subjects with multiple visits:  56

In [11]:

# optaining automatically info to save the file
lst_population = infoSupportFile.get_present_populations()
#lst_population = ['ADNI4']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

In [12]:

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

AMPRION

In [13]:
file_code = 'AMPRION_ASYN_SAA' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['Result']
# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'amprion' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
renamed_df.head()

renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  20
Adopted visit selection strategy:
 Equal values    20
Name: count, dtype: int64
Nessuna regione Tau disponibile — TAU_METAROI non creata.

    RID    EXAMDATE VISCODE  VISIT_MONTH Amprion_Result   METHOD  Npositive
0  5282  2013-09-09      bl            0     Detected-1  amprion          1
1  5012  2012-12-12      bl            0   Not_Detected  amprion          0
2  4394  2012-02-02      bl            0   Not_Detected  amprion          0
3  4214  2011-10-10      bl            0   Not_Detected  amprion          0
4  2378  2011-07-07      bl            0   Not_Detected  amprion          0

In [16]:
tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

totale subject: 1638
subjects with multiple visits:  0

In [17]:
lst_population = ['ADNI1', 'ADNIGO','ADNI3', 'ADNI2']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

BAIPETNMRCFTP

In [19]:
file_code = 'BAIPETNMRCFTP' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['TAU_METAROI', 'ENTORHINAL_SUVR', 'INFERIOR_TEMPORAL_SUVR', 'MODALITY' ]
# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
#datefix_df['METHOD'] = 'simoa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()

renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
TAU_METAROI già presente nel dataset. Nessuna modifica eseguita.

,COHORT,RID,VISCODE,VISIT_MONTH,EXAMDATE,METHOD,ENTORHINAL_SUVR,INFERIOR_TEMPORAL_SUVR,TAU_METAROI,Tpositive
0,ADNI3,21,m144,0,2018-02-02,ftp,1.1234,1.3424,1.2242,0
1,ADNI3,31,m150,0,2018-04-24,ftp,1.1867,1.1618,1.1468,0
2,ADNI3,31,m162,12,2019-04-23,ftp,1.2269,1.1375,1.1242,0
3,ADNI3,56,m144,0,2018-02-20,ftp,1.2735,1.3301,1.2984,1
4,ADNI3,56,m156,11,2019-01-10,ftp,1.2803,1.3603,1.3032,1

In [20]:
var_of_interest = ['TAU_METAROI', 'ENTORHINAL_SUVR', 'INFERIOR_TEMPORAL_SUVR' ]
df_interest = final_df[final_df['METHOD']=='ftp'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)
new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
                       1° percentile 99° percentile
TAU_METAROI                   0.9874         2.4291
ENTORHINAL_SUVR               0.8994         1.9436
INFERIOR_TEMPORAL_SUVR         1.012         2.4746
totale subject: 772
subjects with multiple visits:  266

In [21]:
# optaining automatically info to save the file
lst_population = infoSupportFile.get_present_populations()
#lst_population = ['ADNI3', 'ADNI2']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

In [22]:

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

FNIH_PLASMA_PTAU_PROJECT

In [23]:
file_code = 'FNIH_PLASMA_PTAU_PROJECT' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['PTAU_181', 'IMMUNOASSAY']

# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
#datefix_df['METHOD'] = 'simoa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()


renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  121
Adopted visit selection strategy:
 VISITCODE priority    130
Name: count, dtype: int64
Nessuna regione Tau disponibile — TAU_METAROI non creata.

   COHORT   RID VISCODE  VISIT_MONTH    EXAMDATE  PT181_PL METHOD  Tpositive
0   ADNI1    31    m120            0  2016-01-27      47.1  simoa          0
1   ADNI2  4385     m48            0  2016-01-19      37.5  simoa          0
2   ADNI2  4354     m48            0  2016-02-04      14.1  simoa          0
3   ADNI1   150    m120            0  2016-03-16      71.8  simoa          0
4  ADNIGO  2200     m60            0  2016-03-03      12.2  simoa          0

In [24]:
final_df['METHOD'].unique()

array(['simoa', 'lumipulse'], dtype=object)

In [25]:
var_of_interest = ['PT181_PL']
df_interest=final_df[final_df['METHOD']=='simoa'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
         1° percentile 99° percentile
PT181_PL         6.262         86.814
totale subject: 121
subjects with multiple visits:  9

In [26]:
# optaining automatically info to save the file
lst_population = infoSupportFile.get_present_populations()
#lst_population = ['ADNI3', 'ADNI2']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

CSFALPHASYN

In [28]:
file_code = 'CSFALPHASYN' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['ALPHA_SYN']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = None,
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'luminex' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()


renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

VISCODE reference is not present in the dataframe, it will not be used for the visit selection
Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
Nessuna regione Tau disponibile — TAU_METAROI non creata.

   VISIT_MONTH  RID    EXAMDATE  COHORT  ALPHA_SYN   METHOD  Npositive
0            0    3  2005-09-12  ADNI 1       0.53  luminex          0
1            0    4  2005-11-22  ADNI 1       0.25  luminex          0
2            0    5  2005-09-07  ADNI 1       1.92  luminex          0
3            0    8  2005-09-19  ADNI 1       0.69  luminex          0
4            0   10  2005-11-10  ADNI 1       0.57  luminex          0

In [29]:
var_of_interest = ['ALPHA_SYN']
df_interest=final_df[final_df['METHOD']=='luminex'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
          1° percentile 99° percentile
ALPHA_SYN           0.2         5.2608
totale subject: 389
subjects with multiple visits:  0

In [31]:
# optaining automatically info to save the file
lst_population = ['ADNI1']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

In [32]:

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

UBERKELEY TAU 6 MM

In [34]:
file_code = 'UCBERKELEY_TAU_6MM' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['CTX_ENTORHINAL_SUVR', 'CTX_FUSIFORM_SUVR', 'CTX_INFERIORTEMPORAL_SUVR', 'CTX_INFERIORPARIETAL_SUVR', 'CTX_PRECUNEUS_SUVR','CTX_PARAHIPPOCAMPAL_SUVR', 'CTX_MIDDLETEMPORAL_SUVR', 'CTX_LATERALOCCIPITAL_SUVR'  ]


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['SCANDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'SCANDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
#datefix_df['METHOD'] = 'simoa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()

renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
TAU_METAROI calcolata usando: ENTORHINAL_SUVR, INFERIOR_TEMPORAL_SUVR, FUSIFORM_SUVR, PARAHIPPOCAMPAL_SUVR

,RID,VISCODE,VISIT_MONTH,METHOD,WARNING,ENTORHINAL_SUVR,CTX_ENTORHINAL_VOLUME,CSF_SUVR,CSF_VOLUME,FUSIFORM_SUVR,...,CTX_LATERALOCCIPITAL_VOLUME,MIDDLETEMPORAL_SUVR,CTX_MIDDLETEMPORAL_VOLUME,PARAHIPPOCAMPAL_SUVR,CTX_PARAHIPPOCAMPAL_VOLUME,PRECUNEUS_SUVR,CTX_PRECUNEUS_VOLUME,TAU_METAROI,Apositive,Tpositive
0,21,m144,0,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.184,2647.0,1.236,1140.0,1.205,...,18275.0,1.268,18095.0,1.085,3571.0,1.100,15740.0,1.19125,1,0
1,21,m228,86,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.208,2647.0,0.939,1140.0,1.187,...,18275.0,1.249,18095.0,1.080,3571.0,1.092,15740.0,1.19350,0,0
2,31,m150,0,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.298,2088.0,1.098,1312.0,1.191,...,19643.0,1.137,18301.0,1.146,3808.0,1.152,17688.0,1.19650,1,0
3,31,m162,12,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.288,2186.0,1.021,1306.0,1.163,...,18885.0,1.070,16782.0,1.168,3678.0,1.130,17879.0,1.18825,1,0
4,56,m144,0,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.353,3608.0,1.032,1178.0,1.281,...,18793.0,1.258,15066.0,1.218,3727.0,1.231,17497.0,1.28275,1,1

In [35]:
var_of_interest = [
'TAU_METAROI', 'ENTORHINAL_SUVR',
'CSF_SUVR',
'FUSIFORM_SUVR',
'INFERIORPARIETAL_SUVR',
'INFERIOR_TEMPORAL_SUVR',
'LATERALOCCIPITAL_SUVR',
'MIDDLETEMPORAL_SUVR',
'PARAHIPPOCAMPAL_SUVR',
'PRECUNEUS_SUVR']

df_interest=final_df[final_df['METHOD']=='unknown'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
                       1° percentile 99° percentile
TAU_METAROI                   0.8223         3.4153
ENTORHINAL_SUVR               0.7604         3.3055
CSF_SUVR                      0.6384         1.3087
FUSIFORM_SUVR                 0.8277         3.7355
INFERIORPARIETAL_SUVR         0.8252         3.5348
INFERIOR_TEMPORAL_SUVR        0.8614         3.7954
LATERALOCCIPITAL_SUVR         0.9136         3.8519
MIDDLETEMPORAL_SUVR            0.856         3.3217
PARAHIPPOCAMPAL_SUVR          0.7186         2.9888
PRECUNEUS_SUVR                0.7518         2.7666
totale subject: 1346
subjects with multiple visits:  547

In [37]:
# optaining automatically info to save the file
lst_population = ['ADNI3', 'ADNI2', 'ADNI4']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

In [39]:

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

BLENNOWCSFNFL

In [42]:
file_code = 'BLENNOWCSFNFL' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['CSFNFL']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'elisa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()


renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  16
Adopted visit selection strategy:
 VISITCODE priority    16
Name: count, dtype: int64
Nessuna regione Tau disponibile — TAU_METAROI non creata.

   RID VISCODE  VISIT_MONTH    EXAMDATE  NFL_CSF COMMENTS METHOD  Npositive
0    3      bl            0  2005-09-12     2641      NaN  elisa          1
1    4      bl            0  2005-11-08      602      NaN  elisa          1
2    5      bl            0  2005-09-07      951      NaN  elisa          1
3    8      bl            0  2005-09-19     1382      NaN  elisa          1
4   10      bl            0  2005-11-10     1088      NaN  elisa          1

In [43]:
var_of_interest = ['NFL_CSF']
df_interest=final_df[final_df['METHOD']=='elisa'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
        1° percentile 99° percentile
NFL_CSF        507.86        5897.82
totale subject: 399
subjects with multiple visits:  0

In [45]:
lst_population = ['ADNI1']
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

BLENNOWPLASMATAU

In [52]:
file_code = 'BLENNOWPLASMATAU' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['PLASMATAU']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'simoa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()


renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
Nessuna regione Tau disponibile — TAU_METAROI non creata.

   RID VISCODE  VISIT_MONTH    EXAMDATE  TTAU_PL METHOD  Tpositive
0    2      bl            0  2005-09-08     2.41  simoa          0
1    3      bl            0  2005-09-12     3.84  simoa          0
2    4      bl            0  2005-11-08     3.76  simoa          0
3    5      bl            0  2005-09-07     3.81  simoa          0
4    6      bl            0  2005-11-29     2.86  simoa          0

In [53]:
var_of_interest = ['TTAU_PL']
df_interest=final_df[final_df['METHOD']=='simoa'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
        1° percentile 99° percentile
TTAU_PL         0.357         8.3572
totale subject: 575
subjects with multiple visits:  0

In [54]:
# optaining automatically info to save the file
lst_population = ['ADNI1']

In [55]:
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

BLENNOWPLASMANFL

In [58]:
file_code = 'BLENNOWPLASMANFL' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['PLASMA_NFL']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'elisa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  47
Adopted visit selection strategy:
 VISITCODE priority    51
Equal values           1
Name: count, dtype: int64
Nessuna regione Tau disponibile — TAU_METAROI non creata.

   RID VISCODE  VISIT_MONTH    EXAMDATE  NFL_PL METHOD  Npositive
0    2     m60            0  2010-09-22    25.3  elisa          0
1    2     m72           12  2011-09-19    30.9  elisa          0
2    2     m84           24  2012-09-26    34.1  elisa          0
3    2     m96           36  2013-09-09    35.3  elisa          0
4    8     m60            0  2010-09-27   196.3  elisa          0

In [59]:
var_of_interest = ['NFL_PL']
df_interest=final_df[final_df['METHOD']=='elisa'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
       1° percentile 99° percentile
NFL_PL          12.6        138.252
totale subject: 1191
subjects with multiple visits:  1033

In [61]:
# optaining automatically info to save the file
lst_population = ['ADNI1', 'ADNIGO', 'ADNI2']

In [62]:
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

UGOTptau181

In [63]:
file_code = 'UGOTPTAU181' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['PLASMAPTAU181']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'simoa' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  47
Adopted visit selection strategy:
 VISITCODE priority    52
Name: count, dtype: int64
Nessuna regione Tau disponibile — TAU_METAROI non creata.

   RID VISCODE  VISIT_MONTH    EXAMDATE  PT181_PL METHOD  Tpositive
0    2     m60            0  2010-09-22    11.939  simoa          0
1    2     m72           12  2011-09-19    12.936  simoa          0
2    2     m84           24  2012-09-26    13.563  simoa          0
3    2     m96           36  2013-09-09    15.506  simoa          0
4    8     m60            0  2010-09-27    18.305  simoa          0

In [65]:
var_of_interest = ['PT181_PL']
df_interest=final_df[final_df['METHOD']=='simoa'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))
tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)
new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
         1° percentile 99° percentile
PT181_PL        2.1752        61.8476
totale subject: 1191
subjects with multiple visits:  1033

In [67]:
# optaining automatically info to save the file
lst_population = ['ADNI1', 'ADNI2', 'ADNIGO']

In [68]:
new_file_name = dataCleaner.file_versions_name(file_name=file_name, suffix='_01')

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

UPENNPLASMA

In [72]:
file_code = 'UPENNPLASMA' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['AB40', 'AB42']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
no_none_df['VISIT_MONTH'] = no_none_df['VISCODE'].apply(lambda x: dataCleaner.convert_visitcode_to_int(x))
# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
no_none_df['METHOD'] = 'unknown' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(no_none_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Nessuna regione Tau disponibile — TAU_METAROI non creata.

   RID VISCODE  AB40_PL  AB42_PL  VISIT_MONTH   METHOD  Apositive
0    5      bl    246.1     46.7            0  unknown          1
1    5     m12      NaN     45.7           12  unknown          1
2    5     m24      NaN     48.0           24  unknown          1
3    5     m36    221.2     46.4           36  unknown          1
4    6      bl    289.0     44.3            0  unknown          1

In [73]:
var_of_interest = ['AB40_PL', 'AB42_PL']
df_interest=final_df[final_df['METHOD']=='unknown'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
        1° percentile 99° percentile
AB40_PL        36.614          281.8
AB42_PL          11.6           68.4
totale subject: 731
subjects with multiple visits:  730

In [74]:
# optaining automatically info to save the file
#lst_population = infoSupportFile.get_present_populations()
lst_population = ['ADNI1']

In [75]:

# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

UPENN_PLASMA_FUJIREBIO_QUANTERIX

In [77]:
file_code = 'UPENN_PLASMA_FUJIREBIO_QUANTERIX' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['pT217_F', 'AB42_F', 'AB40_F', 'AB42_AB40_F', 'pT217_AB42_F', 'NfL_Q', 'GFAP_Q' ]


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['EXAMDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'EXAMDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
#datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
datefix_df['METHOD'] = 'quanterix' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
Nessuna regione Tau disponibile — TAU_METAROI non creata.

,COHORT,RID,VISCODE,VISIT_MONTH,EXAMDATE,PT217_PL,AB42_PL,AB40_PL,AB4240_PL,PT217_AB42_PL,NFL_PL,GFAP,METHOD,Apositive,Tpositive,Npositive
0,ADNI1,2,bl,0,2005-09-08,0.199,27.92,324.12,0.086100,0.007130,14.9,94.6,quanterix,1,0,0
1,ADNI1,8,bl,0,2005-09-19,0.152,27.90,296.53,0.094088,0.005448,26.6,141.1,quanterix,1,0,1
2,ADNI2,8,m120,121,2015-10-29,0.235,7.24,70.00,0.103429,0.032459,55.8,289.1,quanterix,1,0,1
3,ADNI1,10,bl,0,2005-11-10,0.472,24.44,332.15,0.073581,0.019313,26.5,194.3,quanterix,1,0,1
4,ADNI1,10,m24,24,2007-11-07,0.586,19.61,288.14,0.068057,0.029883,30.2,221.3,quanterix,1,0,1

In [78]:
var_of_interest = ['PT217_PL', 'AB42_PL','AB40_PL',	'AB4240_PL','PT217_AB42_PL', 'NFL_PL',	'GFAP']
df_interest=final_df[final_df['METHOD']=='quanterix'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
              1° percentile 99° percentile
PT217_PL              0.038         1.5482
AB42_PL             11.6257        44.4181
AB40_PL            141.5576       542.3328
AB4240_PL            0.0582         0.1205
PT217_AB42_PL        0.0015         0.0719
NFL_PL               5.9189         84.123
GFAP                43.3029        575.668
totale subject: 1303
subjects with multiple visits:  386

In [ ]:
# optaining automatically info to save the file
lst_population = infoSupportFile.get_present_populations()
#lst_population = ['ADNI1']
# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

UCBERKELEY_TAUPVC_6MM

In [81]:
file_code = 'UCBERKELEY_TAUPVC_6MM' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['CTX_PRECUNEUS_SUVR', 'CTX_PARAHIPPOCAMPAL_SUVR', 'CTX_INFERIORPARIETAL_SUVR', 'CTX_MIDDLETEMPORAL_SUVR', 'CTX_LATERALOCCIPITAL_SUVR', 'CTX_FUSIFORM_SUVR', 'CTX_ENTORHINAL_SUVR', 'CTX_INFERIORTEMPORAL_SUVR']


# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['SCANDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'SCANDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
#datefix_df['METHOD'] = 'quanterix' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  0
Adopted visit selection strategy:
 Series([], Name: count, dtype: int64)
TAU_METAROI calcolata usando: ENTORHINAL_SUVR, INFERIOR_TEMPORAL_SUVR, FUSIFORM_SUVR, PARAHIPPOCAMPAL_SUVR

,RID,VISCODE2,VISIT_MONTH,SCANDATE,METHOD,WARNING,ENTORHINAL_SUVR,CTX_ENTORHINAL_VOLUME,CSF_SUVR,CSF_VOLUME,...,CTX_LATERALOCCIPITAL_VOLUME,MIDDLETEMPORAL_SUVR,CTX_MIDDLETEMPORAL_VOLUME,PARAHIPPOCAMPAL_SUVR,CTX_PARAHIPPOCAMPAL_VOLUME,PRECUNEUS_SUVR,CTX_PRECUNEUS_VOLUME,TAU_METAROI,Apositive,Tpositive
0,21,m144,0,2018-02-02,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.258,2647.0,0.419,1140.0,...,18275.0,1.246,18095.0,1.041,3571.0,1.249,15740.0,1.2410,1,1
1,21,m228,86,2025-03-24,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.478,2647.0,0.273,1140.0,...,18275.0,1.325,18095.0,1.169,3571.0,1.297,15740.0,1.3560,1,1
2,31,m150,0,2018-04-24,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.413,2088.0,0.351,1312.0,...,19643.0,1.403,18301.0,1.428,3808.0,1.428,17688.0,1.4240,1,1
3,31,m162,12,2019-04-23,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.409,2186.0,0.420,1306.0,...,18885.0,1.256,16782.0,1.367,3678.0,1.290,17879.0,1.3385,1,1
4,56,m144,0,2018-02-20,FTP,DO NOT COMPARE SUVRs ACROSS TRACERS,1.810,3608.0,0.477,1178.0,...,18793.0,1.428,15066.0,1.352,3727.0,1.309,17497.0,1.5050,1,1

In [82]:
final_df['METHOD'].unique()

array(['FTP', 'unknown'], dtype=object)

In [83]:
var_of_interest = [
'TAU_METAROI', 'ENTORHINAL_SUVR',
'CSF_SUVR',
'FUSIFORM_SUVR',
'INFERIORPARIETAL_SUVR',
'INFERIOR_TEMPORAL_SUVR',
'LATERALOCCIPITAL_SUVR',
'MIDDLETEMPORAL_SUVR',
'PARAHIPPOCAMPAL_SUVR',
'PRECUNEUS_SUVR']

df_interest=final_df[final_df['METHOD']=='FTP'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
                       1° percentile 99° percentile
TAU_METAROI                   0.9774         3.2309
ENTORHINAL_SUVR               0.8762          2.958
CSF_SUVR                      0.1678         0.6292
FUSIFORM_SUVR                 0.9675         3.8654
INFERIORPARIETAL_SUVR         0.9378          4.365
INFERIOR_TEMPORAL_SUVR        1.0608         4.0903
LATERALOCCIPITAL_SUVR         0.8988         4.5803
MIDDLETEMPORAL_SUVR           0.9698         3.7738
PARAHIPPOCAMPAL_SUVR          0.8852         2.8173
PRECUNEUS_SUVR                 0.878         3.6718
totale subject: 1219
subjects with multiple visits:  504

In [85]:
# optaining automatically info to save the file
lst_population = ['ADNI2', 'ADNI3', 'ADNI4']

In [86]:
# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)

UCBERKELEY_AMY_6MM

In [90]:
file_code = 'UCBERKELEY_AMY_6MM' 
search = client.query_files(
    query={
        'custom.level' : 'raw',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],
    extract_zip=True
)

file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)

# Important columns
columns_must_be_verified = ['AMYLOID_STATUS', 'AMYLOID_STATUS_COMPOSITE_REF', 'CENTILOIDS', 'SUMMARY_SUVR', 'CTX_ENTORHINAL_SUVR', 'CTX_INFERIORTEMPORAL_SUVR']

# Fixing unkown values and delating rows with no relevant data
no_unknow_df = dataCleaner.replace_unknown_values(df_new)
no_none_df = dataCleaner.drop_if_all_none(no_unknow_df, columns_must_be_verified)

# Finding the exam code
datefix_df = dataCleaner.to_date_format(no_none_df, ['SCANDATE'])
datefix_df = dataCleaner.find_exam_code(
    datefix_df,
    date_column = 'SCANDATE',
    viscode_reference = 'VISCODE2',
    patient_id_column = 'RID',
    essential_variables= columns_must_be_verified)

# Harmonize method column
datefix_df = dataCleaner.ensure_method_column(datefix_df, default_method='unknown')
#datefix_df['METHOD'] = 'quanterix' # write method manually, if not known unknown

#Filtering variables
datefix_df= dataCleaner.filter_variables(datefix_df, list(zip_files.keys())[0], new_var=['VISIT_MONTH', 'METHOD'], prefix='raw')  

# Assign new names to variables
new_support_file_path = 'ADNI_variables_cleaned_BB'
renamed_df, new_support_file = dataCleaner.new_variable_names(new_support_file_path+'.xlsx', datefix_df, file_code)
#renamed_df.head()
renamed_df = dataCleaner.ensure_tau_metaroi(renamed_df)
AbT_df, ratios_var = dataCleaner.get_abeta_tau_ratios(renamed_df)

# Now pass the DataFrame to the get_ATN_profile function
final_df, ATN_var = dataCleaner.get_ATN_profile(AbT_df, "cutoffs.json")
final_df.head()  # This will show the resulting DataFrame

Number of patients with duplicate dates:  6
Adopted visit selection strategy:
 Equal values    6
Name: count, dtype: int64
TAU_METAROI calcolata usando: ENTORHINAL_SUVR, INFERIOR_TEMPORAL_SUVR

,RID,VISCODE,VISIT_MONTH,EXAMDATE,METHOD,WARNING,AMYLOID_STATUS,AMYLOID_STATUS_COMPOSITE_REF,AMY_CENTILOIDS,SUMMARY_SUVR,SUMMARY_VOLUME,ENTORHINAL_SUVR,CTX_ENTORHINAL_VOLUME,INFERIOR_TEMPORAL_SUVR,CTX_INFERIORTEMPORAL_VOLUME,TAU_METAROI,Apositive,Tpositive
0,767,m48,0,2011-01-20,FBP,USE CENTILOIDS (NOT SUVRs) TO COMPARE ACROSS T...,0.0,0.0,-5.0,0.978,NaN,NaN,NaN,NaN,NaN,NaN,0,<NA>
1,767,m72,19,2012-08-22,FBP,USE CENTILOIDS (NOT SUVRs) TO COMPARE ACROSS T...,0.0,0.0,1.0,1.011,NaN,NaN,NaN,NaN,NaN,NaN,0,<NA>
2,767,m126,76,2017-05-18,FBB,USE CENTILOIDS (NOT SUVRs) TO COMPARE ACROSS T...,0.0,0.0,11.0,1.034,247808.0,1.062,2691.0,1.101,15070.0,1.0815,0,0
3,767,m150,98,2019-03-27,FBP,USE CENTILOIDS (NOT SUVRs) TO COMPARE ACROSS T...,0.0,0.0,15.0,1.085,250829.0,1.080,2842.0,1.227,15157.0,1.1535,0,0
4,767,m180,126,2021-07-27,FBP,USE CENTILOIDS (NOT SUVRs) TO COMPARE ACROSS T...,0.0,0.0,6.0,1.038,237281.0,1.045,2458.0,1.166,15396.0,1.1055,0,0

In [56]:
final_df['METHOD'].unique()

array(['FBP', 'FBB', 'NAV'], dtype=object)

In [91]:
var_of_interest = [
'TAU_METAROI', 'AMY_CENTILOIDS','ENTORHINAL_SUVR',
'SUMMARY_SUVR',
'INFERIOR_TEMPORAL_SUVR']

df_interest=final_df[final_df['METHOD']=='NAV'][var_of_interest].copy(deep=True)
percentile_df = pd.DataFrame(index=df_interest.keys(), columns=['1° percentile',  '99° percentile', ])

for var in df_interest.keys():
    p1 = df_interest[var].quantile(0.01)
    p99 = df_interest[var].quantile(0.99)

    percentile_df.loc[var, '1° percentile'] = round(p1, 4)
    percentile_df.loc[var, '99° percentile'] = round(p99, 4)

print("Confronto tra percentili calcolati e valori di riferimento:")
print(percentile_df.dropna(how='all'))

tot_sub = len(final_df['RID'].unique())
print('totale subject:', tot_sub)
multiple_visists = (final_df['RID'].value_counts() > 1).sum()
print('subjects with multiple visits: ', multiple_visists)

new_support_file = update_variables_support_file(final_df, new_support_file, file_code)
infoSupportFile = InfoSupportFile(new_support_file, final_df, file_name)

for key in final_df.keys():
    if key in new_support_file[new_support_file['file_code'] == file_code]['variable_code'].values:
        new_support_file = infoSupportFile.get_varible_info(key)

save_df(new_support_file, new_support_file_path)

Confronto tra percentili calcolati e valori di riferimento:
                       1° percentile 99° percentile
TAU_METAROI                   0.9743         1.9762
AMY_CENTILOIDS                 -3.36         153.52
ENTORHINAL_SUVR               0.9562         1.5686
SUMMARY_SUVR                  0.9347         2.3755
INFERIOR_TEMPORAL_SUVR        0.9837          2.424
totale subject: 2164
subjects with multiple visits:  1141

In [92]:
# optaining automatically info to save the file
lst_population = ['ADNI1', 'ADNI2', 'ADNI3', 'ADNI4', 'ADNIGO']

In [93]:
# Upload the file into the Data Lake
result = client.upload_dataframe(
    df=final_df,
    object_name=new_file_name,
    prefix='cleaned/single_file/',
    metadata={
        'population':lst_population,
        'level': 'cleaned_01',
        'file_code': file_code,
        'source': 'ADNI'
    }
)