In [8]:
from dl_client import DatalakeClient
import pandas as pd

client = DatalakeClient()

In [18]:
search = client.query_files(query={'custom.level': 'raw', 'custom.file_code': ['BAIPETNMRCFTP']})
files = [x['filename'] for x in search['included_files']]
print(len(files))# Print the number of files found

1

In [19]:
print(files)

['BAIPETNMRCFTP_08_17_22_11Aug2025.csv']

In [20]:
zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True
)

In [22]:
file_name = list(zip_files.keys())[0] #[1] in quello di chiara
print(file_name)
dataset = zip_files[file_name]

df_new = dataset.copy(deep=True)
df_new.head()

BAIPETNMRCFTP_08_17_22_11Aug2025.csv

,ORIGPROT,COLPROT,RID,VISCODE,VISCODE2,EXAMDATE,LONIUID,RUNDATE,STATUS,MODALITY,ENTORHINAL_SUVR,INFERIOR_TEMPORAL_SUVR,TAU_METAROI,update_stamp
0,ADNI1,ADNI3,21,init,m144,2018-02-02,964025,2022-07-15,Complete,Flortaucipir,1.1234,1.3424,1.2242,2022-08-26 10:10:21.0
1,ADNI1,ADNI3,31,y1,m162,2019-04-23,1158506,2022-07-15,Complete,Flortaucipir,1.2269,1.1375,1.1242,2022-08-26 10:10:21.0
2,ADNI1,ADNI3,31,init,m150,2018-04-24,989589,2022-07-15,Complete,Flortaucipir,1.1867,1.1618,1.1468,2022-08-26 10:10:21.0
3,ADNI1,ADNI3,56,y1,m156,2019-01-10,1118612,2022-07-15,Complete,Flortaucipir,1.2803,1.3603,1.3032,2022-08-26 10:10:21.0
4,ADNI1,ADNI3,56,init,m144,2018-02-20,968713,2022-07-15,Complete,Flortaucipir,1.2735,1.3301,1.2984,2022-08-26 10:10:21.0

In [29]:
296/832

0.3557692307692308

##  Check metadata di tutti i file uno per uno

In [ ]:
i =9

In [23]:
file_name = 'BAIPETNMRCFTP_08_17_22_11Aug2025.csv' #files[0]
print(file_name, '----------')
metadata = client.get_metadata(object_name='raw/'+file_name)
display(metadata['metadata']['custom'])
i += 1

BAIPETNMRCFTP_08_17_22_11Aug2025.csv ----------

{'download_type': 'study_files',
 'file_code': 'BAIPETNMRCFTP',
 'level': 'raw',
 'population': ['2', '3'],
 'source': 'ADNI'}

In [24]:
zip_files = client.download_file(object_name='raw/'+file_name,  
    extract_zip=True
)

In [25]:
file_code = 'ADNIMERGE'
search = client.query_files(
    query={
        'custom.level' : 'cleaned_01',
        'custom.file_code': file_code
    }
)

zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True
)

In [26]:
file_name = list(zip_files.keys())[0]
dataset = zip_files[file_name]
zip_files

{'ADNIMERGE_25Jul2025_01.csv':        AGE_bl  VISIT_MONTH        PTID   RID  COHORT    EXAMDATE   AGE  \
 0        74.3            0  011_S_0002     2   ADNI1  2005-09-08  74.3
 1        74.3            6  011_S_0002     2   ADNI1  2006-03-06  74.7
 2        74.3           36  011_S_0002     2   ADNI1  2008-08-27  77.2
 3        74.3           60  011_S_0002     2  ADNIGO  2010-09-22  79.3
 4        74.3           72  011_S_0002     2   ADNI2  2011-09-19  80.3
 ...       ...          ...         ...   ...     ...         ...   ...
 11453    65.6            0  033_S_7114  7114   ADNI3  2022-11-16  65.6
 11454    61.4            0  053_S_7086  7086   ADNI3  2022-11-07  61.4
 11455    64.6            0  035_S_7049  7049   ADNI3  2022-09-13  64.6
 11456    68.9            0  082_S_7117  7117   ADNI3  2023-01-12  68.9
 11457    62.1            0  035_S_7121  7121   ADNI3  2023-03-22  62.1

        GENDER  EDUCAT  ETHNICITY  ...  RAVLT_immediate   FAQ  MOCA  \
 0           1      16        0.0  ...             44.0   0.0   NaN
 1           1      16        0.0  ...             40.0   0.0   NaN
 2           1      16        0.0  ...             34.0   0.0   NaN
 3           1      16        0.0  ...             37.0   0.0  23.0
 4           1      16        0.0  ...             42.0   0.0  22.0
 ...       ...     ...        ...  ...              ...   ...   ...
 11453       0      17        0.0  ...             59.0   3.0  30.0
 11454       1      12        0.0  ...             22.0  15.0  19.0
 11455       0      12        1.0  ...             31.0   0.0  23.0
 11456       0      18        0.0  ...             45.0   0.0  26.0
 11457       1      17        0.0  ...             48.0   1.0  28.0

        Ventricles  Hippocampus  Entorhinal  Fusiform  MidTemp        ICV  DX
 0        118233.0       8336.0      4177.0   16559.0  27936.0  1984660.0   0
 1             NaN          NaN         NaN       NaN      NaN        NaN   0
 2             NaN          NaN         NaN       NaN      NaN        NaN   0
 3             NaN          NaN         NaN       NaN      NaN        NaN   0
 4             NaN          NaN         NaN       NaN      NaN        NaN   0
 ...           ...          ...         ...       ...      ...        ...  ..
 11453     15983.4       7717.3      3701.0   17860.0  16735.0  1326860.0   0
 11454         NaN          NaN         NaN       NaN      NaN        NaN   1
 11455         NaN          NaN         NaN       NaN      NaN        NaN   1
 11456         NaN          NaN         NaN       NaN      NaN        NaN   1
 11457         NaN          NaN         NaN       NaN      NaN        NaN   1

 [11458 rows x 29 columns]}

In [27]:

zip_files = client.download_file(
    search['object_name'],  
    extract_zip=True)

In [28]:
print(zip_files.keys())

dict_keys(['ADNIMERGE_25Jul2025_01.csv'])

In [29]:
file_name = 'ADNIMERGE_25Jul2025_01.csv'
df = zip_files[file_name]

In [30]:
metadata = client.get_metadata(
            object_name = 'articles/Biel 2021 ADNI preclin MCI AD imaging Braak staging cogn longit predict.pdf'
        )
print(metadata['metadata'])

{'_id': '6838828ff99891d54bb44883', 'bucket_name': 'aind', 'content_type': 'application/pdf', 'created_at': '2025-05-29T15:51:43.525784', 'custom': {'author': 'Biel', 'keywords': ['ADNI', 'preclin', 'MCI', 'AD', 'imaging', 'Braak', 'staging', 'cogn', 'longit', 'predict'], 'year': '2021'}, 'filename': 'Biel_2021_ADNI_preclin_MCI_AD_imaging_Braak_staging_cogn_longit_predict.pdf', 'last_modified': '2025-05-29T15:51:43.443935', 'object_name': 'articles/Biel 2021 ADNI preclin MCI AD imaging Braak staging cogn longit predict.pdf', 'path': '/data/aind/articles/Biel 2021 ADNI preclin MCI AD imaging Braak staging cogn longit predict.pdf', 's3_url': 'http://131.175.204.159:9000/aind/articles/Biel%202021%20ADNI%20preclin%20MCI%20AD%20imaging%20Braak%20staging%20cogn%20longit%20predict.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20250529%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250529T155143Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=9d7b5fec764c2b503c460b66964bde1e49a67ab7ef6af66106210fb234b16d19', 'size_bytes': 2808589, 'status': 'active'}

In [31]:
df

,AGE_bl,VISIT_MONTH,PTID,RID,COHORT,EXAMDATE,AGE,GENDER,EDUCAT,ETHNICITY,...,RAVLT_immediate,FAQ,MOCA,Ventricles,Hippocampus,Entorhinal,Fusiform,MidTemp,ICV,DX
0,74.3,0,011_S_0002,2,ADNI1,2005-09-08,74.3,1,16,0.0,...,44.0,0.0,NaN,118233.0,8336.0,4177.0,16559.0,27936.0,1984660.0,0
1,74.3,6,011_S_0002,2,ADNI1,2006-03-06,74.7,1,16,0.0,...,40.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,74.3,36,011_S_0002,2,ADNI1,2008-08-27,77.2,1,16,0.0,...,34.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,74.3,60,011_S_0002,2,ADNIGO,2010-09-22,79.3,1,16,0.0,...,37.0,0.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,0
4,74.3,72,011_S_0002,2,ADNI2,2011-09-19,80.3,1,16,0.0,...,42.0,0.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11453,65.6,0,033_S_7114,7114,ADNI3,2022-11-16,65.6,0,17,0.0,...,59.0,3.0,30.0,15983.4,7717.3,3701.0,17860.0,16735.0,1326860.0,0
11454,61.4,0,053_S_7086,7086,ADNI3,2022-11-07,61.4,1,12,0.0,...,22.0,15.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,1
11455,64.6,0,035_S_7049,7049,ADNI3,2022-09-13,64.6,0,12,1.0,...,31.0,0.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,1
11456,68.9,0,082_S_7117,7117,ADNI3,2023-01-12,68.9,0,18,0.0,...,45.0,0.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,1
11457,62.1,0,035_S_7121,7121,ADNI3,2023-03-22,62.1,1,17,0.0,...,48.0,1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,1